language: python
sudo: required
group: edge
addons:
  apt:
    packages:
      - python-dev
      - libmysqlclient-dev
cache:
  pip: true
  directories:
    - $HOME/.nvm/versions/node/
python:
  - 2.7
  # - 3.5
# before-install:
#   - npm -g install npm@latest

services:
  - rabbitmq
addons:
  - mariadb: '10.0'

env:
  - >-
    APP_CONFIG="config.TestingConfig"
    DATABASE_URL=mysql+mysqldb://root@localhost/geokrety_unittest?charset=utf8mb4
    TEST_DATABASE_URL=mysql+mysqldb://root@localhost/geokrety_unittest?charset=utf8mb4
    SERVE_STATIC=true
    MINIO_ACCESS_KEY=access_key
    MINIO_SECRET_KEY=secret_key
    MINIO_ENDPOINT=127.0.0.1:9000
    MINIO_BROWSER=off

before_install:
  # installing newer docker
  - wget https://dl.minio.io/server/minio/release/linux-amd64/minio && chmod +x minio
  - mkdir .vars && ./minio server .vars &
#  # Aglio
#   - npm -g install npm@latest

install:
  # - npm list -g dredd@4.0.0 --depth=0 || npm install -g dredd@4.0.0
  # - npm list -g aglio --depth=0 || npm install -g aglio
  - pip install -r requirements/tests.txt
before_script:
  - mysql -e 'FLUSH TABLES; DROP DATABASE IF EXISTS geokrety_unittest; CREATE DATABASE geokrety_unittest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
script:
  - nosetests tests/ -v --with-coverage --with-id --nologcapture --stop
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then python-codacy-coverage -r coverage.xml; fi'
  # - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then cat docs/*.apib > apiary.apib; dredd; fi'  # TODO: Enable later, it's quite long during initial dev
  # - 'aglio -i docs/apiary.apib -o docs/index.html --theme-variables slate --theme-full-width --no-theme-condense'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
