language: python
sudo: required
group: edge
addons:
  apt:
    packages:
      - python-dev
      - libmysqlclient-dev
cache:
  pip: true
  directories:
    - $HOME/.nvm/versions/node/v8.4.0/lib
    - $HOME/.nvm/versions/node/v8.4.0/bin/
python:
  #- pypy
  - 2.7
  # - pypy3
  # - 3.3
  # - 3.4
  # - 3.5
before-install:
  - npm -g install npm@latest
install:
  - npm list -g dredd@4.0.0 --depth=0 || npm install -g dredd@4.0.0
  - npm list -g aglio --depth=0 || npm install -g aglio
  - pip install -r requirements/tests.txt
env:
  - >-
    APP_CONFIG="config.TestingConfig"
    DATABASE_URL=mysql+mysqldb://root@localhost/geokrety_unittest
    TEST_DATABASE_URL=mysql+mysqldb://root@localhost/geokrety_unittest
    SERVE_STATIC=true
addons:
  - mariadb: '10.0'
before_script:
  - mysql -e 'CREATE DATABASE geokrety_unittest;'
script:
  - nosetests tests/unittests -v --with-coverage
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then dredd; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python-codacy-coverage -r coverage.xml; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then aglio -i apiary.apib -o docs/output.html --theme-variables slate; fi'
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  on:
    branch: master
