version: '3.3'

configs:
  env-config:
    file: .env.production

networks:
  default:
  traefik_default:
    external:
      name: traefik_default
  func_functions:
    external:
      name: func_functions

secrets:
  basic-auth-user:
    external: true
  basic-auth-password:
    external: true


services:
  api:
    build: .
    image: geokrety_api:latest
    volumes:
      - ./:/src/
    configs:
      - source: env-config
        target: /src/.env
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:api.geokrety.house.kumy.net"
        - "traefik.docker.network=traefik_default"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=5000"
    networks:
      - traefik_default
      - default
    environment:
      - APP_CONFIG=config.ProductionConfig
    command: gunicorn -w 4 -b 0.0.0.0:5000 --reload app:current_app --access-logfile=- --error-logfile=-

  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:minio.geokrety.house.kumy.net"
        - "traefik.docker.network=traefik_default"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=9000"
    volumes:
      - ./vars/minio/data:/data
      - ./vars/minio/config:/root/.minio
    networks:
      - traefik_default
      - default
    environment:
      - "MINIO_ACCESS_KEY=AA26C974817F6DF1439C0"
      - "MINIO_SECRET_KEY=hxjz9Birr5JOIQrS5jWt5N2C2X33knjDXPcwZ7GphQmkjfywqKlnxOxYrwlqUTM"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:rabbit.geokrety.house.kumy.net"
        - "traefik.docker.network=traefik_default"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=15672"
    networks:
      - traefik_default
      - default
    # environment:
    #   RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management path_prefix "/rabbit"'

  connector:
    image: templum/rabbitmq-connector:0.1.0
    environment:
      RMQ_TOPICS: "geokrety.geokret.insert,geokrety.geokret.update"
      RMQ_HOST: "rabbit"
      RMQ_PORT: "5672"
      RMQ_USER: "guest"
      RMQ_PASS: "guest"
      OPEN_FAAS_GW_URL: "http://gateway:8080"
      RMQ_QUEUE: "geokrety"
      RMQ_EXCHANGE: "geokrety"
      basic_auth: "true"
      secret_mount_path:  "/run/secrets/"
    networks:
      - func_functions
      - default
    secrets:
      - basic-auth-user
      - basic-auth-password

  db:
    image: mariadb:10.1.13
    ports:
      - 3306:3306
    deploy:
      labels:
        - "traefik.enable=false"
    volumes:
      - /srv/MYSQL/conf:/etc/mysql/conf.d
      - /srv/MYSQL/databases-5.6:/var/lib/mysql
    networks:
      - traefik_default
      - default
    environment:
      MYSQL_ROOT_PASSWORD: sdfsdf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:adminer.geokrety.house.kumy.net"
        - "traefik.docker.network=traefik_default"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.port=80"
    networks:
      - traefik_default
      - default
