version: '2'
services:

  geokrety-flask:
    container_name: geokrety-flask
    build: .
    restart: always
    ports:
     - "5001:5000"
    volumes:
      - ./:/src/
      - ./.env.production:/src/.env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=geokrety-api-dev"
      - "traefik.frontend.rule=Host:api.geokrety.house.kumy.net"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.docker.network=kumy_default"
      - "traefik.port=5000"
    networks:
      - back
    environment:
      - APP_CONFIG=config.ProductionConfig
    # command: sleep 1000000
    command: gunicorn -w 4 -b 0.0.0.0:5000 --reload app:app


networks:
  back:
    external:
      name: kumy_default
